# https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties

# Gradle Properties
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.daemon=true
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx3G
org.gradle.parallel=true

# Mod Properties
root_package=sayys
mod_id=depthsupdate
mod_name=Depths Update
mod_version=0.1.13
mod_authors=__sayys
mod_credits=
mod_description=Backporting Caves & Cliffs. Deeper worlds with negative coordinates!
mod_logo_path=assets/depthsupdate/icon.png
mod_update_json=https://forge.curseupdate.com/1472501/depthsupdate
mod_url=https://www.curseforge.com/minecraft/mc-mods/depths-update
coremod_plugin_class=sayys.depthsupdate.DepthsUpdateLoadingPlugin
